#!/bin/bash -e
source "${OPENSHIFT_RUBY_DIR}/lib/servers"

function start() {
  bundle exec lita
}

function stop() {
  killall lita
}

function restart() {
  killall lita; bundle exec lita
}

case "$1" in
  start)    start ;;
  stop)     stop ;;
  restart)  restart ;;
  *)        exit 0 ;;
esac
